### DISCUSSION TITLE
怎么使imgaePreview预览的图片宽度达到浏览器窗口最大宽度

### DISCUSSION THREAD

**Discussion by qvani** [youzan/vant#10892] [Q&A]
在imagePreview的API介绍中没看到有关于预览图片大小设置的地方
然而在预览时，图片大小过小，很影响体验
我修改了预览图片相关的css样式
```css
.van-image-preview__swipe-item{
  width:100vw !important;
}
```
这样在png,jpeg等格式中表现良好，能够使图片大小占满屏幕宽度。
但是在Gif这种动图的情况下，不会自动拉伸动图长宽，会在动图右侧留白以达到我设置的100vw的要求

有没有办法解决动图的问题
