### DISCUSSION TITLE
使用vant-cli搭建组件库站点时，如何穿透样式去配置站点的样式呢

### DISCUSSION THREAD

**Discussion by jc-yang** [youzan/vant#11467] [Q&A]
求教~想要自定义组件库预览页面的样式，不知道怎么在组件库项目中去配置网站的样式，如
```css
:root {
    --van-doc-black: #000;
    --van-doc-white: #fff;
    --van-doc-gray-1: #f7f8fa;
    --van-doc-gray-2: #f2f3f5;
    --van-doc-gray-3: #ebedf0;
    --van-doc-gray-4: #dcdee0;
    --van-doc-gray-5: #c8c9cc;
    --van-doc-gray-6: #969799;
    --van-doc-gray-7: #646566;
    --van-doc-gray-8: #323233;
    --van-doc-blue: #1989fa;
    --van-doc-green: #07c160;
    --van-doc-padding: 24px;
    --van-doc-row-max-width: 1680px;
    --van-doc-nav-width: 220px;
    --van-doc-border-radius: 20px;
    --van-doc-simulator-width: 360px;
    --van-doc-simulator-height: 620px;
    --van-doc-header-top-height: 64px;
}
```
这些变量的覆盖，应该在哪里去配置呢?
