### ISSUE TITLE
van-field 组件添加 label slot

### ISSUE THREAD

**Issue by transtone** [youzan/vant#1041]
当前的 label 只能是文本，有时候想和 cell 一样在文字前添加图标，或者用图片替代图标，van-field 就用不上了，只能自己拿 van-field 的源码封装一次，太不方面。能够官方增加一个 label slot 就太好了。

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 1.1.3 版本支持

**Comment by transtone** [comment]
slot是有了，可宽度不能调。
```css
.van-cell__title, .van-cell__value{flex:1;}
```
是不是只把 .van-cel__value 设置 flex:1 就好了？
