### ISSUE TITLE
van-tabs shrink 配合css sticky吸顶 IOS 滚动回弹效果中 vant-tabs消失

### ISSUE THREAD

**Issue by sm0210** [youzan/vant#10550]
### 重现链接

无

### Vant 版本

3.3.1

### 描述一下你遇到的问题。

通过 css sticky实现吸顶，吸顶内容过区域有 van-tabs 并开启了shrink属性 在 IOS 滚动回弹效果中  vant-tabs会消失，普通吸顶内容并没有消失。

### 重现步骤

````html
<div>
    <div class="staticCls">
      <div style="border: 1px solid red; height: 30px;">固定不消失的内容</div>
      <van-tabs shrink>
        <van-tab v-for="index in 14" :title="'选项 ' + index"> </van-tab>
      </van-tabs>
    </div>
    <div style="border: 1px solid red; height:800px;">
      IOS 向上滑动  van-tabs 会消失 <br>
      IOS 向上滑动  van-tabs 会消失 <br>
      IOS 向上滑动  van-tabs 会消失 <br>
    </div>
  </div>
````

````css
.staticCls {
    position: sticky;
    top: 0px;
    background-color: #fff;
}
````

### 设备/浏览器

iPhone12 IOS 15.0.2
