### ISSUE TITLE
ContactCard[Feature Request] Title

### ISSUE THREAD

**Issue by donvie** [youzan/vant#10630]
### What problem does this feature solve?

Can you make a way to add more fields, Because I want to put Address field.

### What does the proposed API look like?

<van-contact-card
  type="edit"
  name="John Snow"
  tel="13000000000"
  address="USA"
  :editable="false"
/>

**Comment by donvie** [comment]
![image](https://user-images.githubusercontent.com/6716238/170400457-37b54869-8969-4977-a6c5-0206abb7bd68.png)

**Comment by donvie** [comment]
> ![image](https://user-images.githubusercontent.com/6716238/170400457-37b54869-8969-4977-a6c5-0206abb7bd68.png)

noted Thank you. How to implement this in the  field component?

**Comment by chenjiahan** [comment]
```css
.van-contact-card:before {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    height: 2px;
    background: repeating-linear-gradient(-45deg,var(--van-warning-color) 0,var(--van-warning-color) 20%,transparent 0,transparent 25%,var(--van-primary-color) 0,var(--van-primary-color) 45%,transparent 0,transparent 50%);
    background-size: 80px;
    content: "";
}
```
