### ISSUE TITLE
[Bug Report] 使用rem后出现莫名其妙的空白

### ISSUE THREAD

**Issue by leewithyuan** [youzan/vant#10651]
### 重现链接
[有空白](https://codesandbox.io/s/flamboyant-kilby-ny0umb?file=/src/components/HelloWorld.vue)

[无空白](https://codesandbox.io/s/cocky-dijkstra-yzt9ou?file=/src/components/HelloWorld.vue)

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

使用了rem后出现莫名其妙的空白，
把body的line-height设置为0好像会消失

但是会有组件收到影响不显示内容 
请问如何解决此问题呢？

在正常情况下 会有间隙空白
![image](https://user-images.githubusercontent.com/91421824/170888151-afa775d6-82ec-4268-a744-102ea672ce85.png)

把line-height设置为0后会消失

但是部分组件无法显示 例如 Area组件
![image](https://user-images.githubusercontent.com/91421824/170888189-6d79112f-eace-41c2-8c39-fc0f24c85128.png)

### 重现步骤

无

**Comment by chenjiahan** [comment]
你可以把 Vant 组件的 line height 再设置回来

```css
[class*='van-'] {
  line-height: normal;
}
```

**Comment by SilentFlute** [comment]
> 

嚯, 这个css选择器是什么啊, 挺厉害啊~

**Comment by SilentFlute** [comment]
@chenjiahan 求指点~

**Comment by chenjiahan** [comment]
CSS Attribute Selectors 哈
https://www.w3schools.com/css/css_attribute_selectors.asp

**Comment by SilentFlute** [comment]
> ```css
> class*=
> ```

嗦嘎, 第一次见这样的class形式的选择器, 666, 谢啦~

**Comment by zehuichan** [comment]
```css

**Comment by zehuichan** [comment]
```css
:not([class*='van-']) {
  line-height: 1.5714285714285714;
}

[class*='van-'] {
  line-height: normal;
}
```
