### ISSUE TITLE
[Bug Report] 阿拉伯语 dir="rtl" 布局下 Tab 标签页无法正常滑动显示

### ISSUE THREAD

**Issue by Tyrone2333** [youzan/vant#11531]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-mro3u5

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

dir="rtl" 布局下 Tab 标签页无法正常滑动显示

点击 标签 2 会 transform: translateX(-500px); 但是 rtl 下要  translateX(500px) 才能正常显示

版本 3.4.6 和 4.0.7 都会

### 重现步骤

1. 点击 tab 标签
2. 内容无法显示

### 设备/浏览器

全部

**Comment by wjw-gavin** [comment]
`vant`目前还不支持`RTL`吧，这需要你自己去兼容。

**Comment by chenjiahan** [comment]
我们暂时没有适配 RTL 的计划，建议先自行处理下

**Comment by cy920820** [comment]
希望增加一个attr 来支持

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant/discussions/11785

**Comment by vivid05** [comment]
> 我们暂时没有适配 RTL 的计划，建议先自行处理下

有好的处理方案吗

**Comment by vivid05** [comment]
> `vant`目前还不支持`RTL`吧，这需要你自己去兼容。

有好的处理方案吗

**Comment by iulo** [comment]
留个临时解决方案：强制把swipe的容器写回`ltr`

```css
  html[dir='rtl'] {
    .van-swipe {
      direction: ltr;
    }
    .van-swipe-item {
      direction: rtl;
    }
  }
```
