### ISSUE TITLE
vant 分页组件, css样式小bug

### ISSUE THREAD

**Issue by ameegle** [youzan/vant#12060]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-8fuq5o?file=/src/App.vue

### Vant 版本

4.4.0

### 描述一下你遇到的问题。

当分页组件选择简单模式(`mode="simple"`)时, `上一页`按钮的右边框不显式, 经过查看时因为如下原因:
```css
.van-pagination {
  &__item {
    &:not(:last-child)::after {
      border-right-width: 0;
    }
  }
}
```

### 重现步骤

无

### 设备/浏览器

all
