### ISSUE TITLE
[Feature Request] 希望vant-list组件支持指定监听的滚动元素

### ISSUE THREAD

**Issue by WeiYuanlin** [youzan/vant#12074]
### 这个功能解决了什么问题？

使用场景如下：
页面有2个滚动区域，类似于如下：
```html
<div class="scrollBox1">
    <div class="scrollheader"></div>
    <div class="scrolbox2" ref="scroller">
      <van-list></van-list>
    </div>
 </div>
```

初始时候的css
```css
.scrollBox1{
  overflow-y: auto;
}
.scrollheader{
  width: 100%;
  height: 200px;
}
.scrolbox2{
  width: 100%;
  overflow: hidden;
  max-height: calc(100vh - 80px);
}
```

后续会将scrolbox2动态设置成可滚动元素，添加一个可滚动样式：
```css
.scrolbox2.scrollable {
  overflow: auto;
}
```
希望可以支持指定van-list的父级.scrolbox2作为监听滚动的元素。而不是初始化时候获取的scrollBox1作为滚动监听

### 你期望的 API 是什么样子的？

```html
      <van-list :scroller="scroller"></van-list>

```
