### ISSUE TITLE
[Feature Request] 希望iconfont使用ios和Android都兼容的格式，如 ttf

### ISSUE THREAD

**Issue by lonffreytu** [youzan/vant#12934]
### 这个功能解决了什么问题？

在代码 https://github.com/youzan/vant/blob/main/packages/vant-icons/src/encode-woff2.less 和 https://github.com/youzan/vant/blob/main/packages/vant-icons/src/index.less 中可以看到现在vant优先使用woff2的字体。但是在Android系统中不支持woff2。导致显示不出图标。如果能使用通用的ttf格式就可以解决这个问题了
以下是开发人员工具上的显示效果
![image](https://github.com/youzan/vant/assets/110774929/51d6d6f9-ac63-4b0d-826b-96d3e635bf31)

以下是Android真机调试的效果
![e09933102080d7ad0fe607c775ad90b](https://github.com/youzan/vant/assets/110774929/00d9e042-a2fe-49d2-b660-6eab2f59668b)

### 你期望的 API 是什么样子的？

无需提供api，只需要修改字体格式

**Comment by inottn** [comment]
不清楚你的项目环境是什么，但是看 woff2 的兼容性还是没问题的
![image](https://github.com/youzan/vant/assets/18509404/ff4d4fce-d0f1-4fe1-bf28-dcd2bbe68a12)

**Comment by inottn** [comment]
不清楚你的项目环境是什么，但是看 woff2 的兼容性还是没问题的
![image](https://github.com/youzan/vant/assets/18509404/ff4d4fce-d0f1-4fe1-bf28-dcd2bbe68a12)

**Comment by lonffreytu** [comment]
> 不清楚你的项目环境是什么，但是看 woff2 的兼容性还是没问题的 ![image](https://private-user-images.githubusercontent.com/18509404/339735560-ff4d4fce-d0f1-4fe1-bf28-dcd2bbe68a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjE2ODYsIm5iZiI6MTcxODM2MTM4NiwicGF0aCI6Ii8xODUwOTQwNC8zMzk3MzU1NjAtZmY0ZDRmY2UtZDBmMS00ZmUxLWJmMjgtZGNkMmJiZTY4YTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwMzYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZTRlODAxMjE0ZTZmMDY2NGYzZjJkNzI0MGZkNmZkZTM0YWNiYWViMzkzM2RmMGYyMTZjMzA3OTBjMjI2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4DJWndOSmPEa5vkS4_SCOgrNHO8Dy7ZiSyn62jUt6oQ)

刚刚测试出来，的确不是woff2的兼容性问题。
在文件中 https://github.com/youzan/vant/blob/main/packages/vant-icons/src/common.less

```less
.van-icon {
  position: relative;
  display: inline-block;
  // compatible with the browser range of Vant 2
  font: normal normal normal 14px/1 'vant-icon';
  font: normal normal normal 14px/1 var(--van-icon-font-family, 'vant-icon');
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;

  &:before {
    display: inline-block;
  }
}
```

这段代码的:before里面加上 `font-family:vant-icon` 即可。很奇怪，我的手机上会出现这个问题。我的真机环境是小米10
![image](https://github.com/youzan/vant/assets/110774929/7bd7afc2-b0eb-47f3-b9ae-189c0e21b3bf)


在自己的小程序代码中可以修改修改miniprogram_npm/@vant/weapp/icon/index.wxss
![image](https://github.com/youzan/vant/assets/110774929/1c4e33ba-6b8c-4fa0-8315-b75a23ea7c54)

希望能够帮助到出现同样问题的朋友
