### ISSUE TITLE
[Feature Request] 微信小程序端，希望van-picker可以提供修改选择框的背景颜色方式

### ISSUE THREAD

**Issue by gin-18** [youzan/vant#13110]
### 这个功能解决了什么问题？

自定义主题时，可以修改选择框的的背景颜色

### 你期望的 API 是什么样子的？

在微信小程序中，选择项的颜色可以修改，但是选择框的颜色无法修改。

```html
<van-picker
    class="my-picker"
    show-toolbar
    columns="{{ openTime }}"
/>
```

```css
.my-picker {
    --picker-background-color: #1e1e2e;
    --picker-confirm-action-color: #89b4fa;
    --picker-cancel-action-color: #bac2de;
    --picker-option-text-color: #cdd6f4;
    --picker-option-selected-text-color: #89b4fa;
}
```

```js
Page({
    data: {
      openTime: ['18:00', '18:30']
    }
})
```

![image](https://github.com/user-attachments/assets/6f04875e-84a9-4f31-ac53-48b23900bfae)
