### ISSUE TITLE
Swipe 组件不显示

### ISSUE THREAD

**Issue by jessetu** [youzan/vant#174]
demo是将高度直接设为200px,。
建议添加
``` css
.van-swipe-item:first-child {
    position: relative;
}
```
这样高度会根据图片等比缩放
