### ISSUE TITLE
引入本地字体图标报错

### ISSUE THREAD

**Issue by Oswald-Tu** [youzan/vant#2066]
以下是我引入的方式：
import 'vant/lib/index.css'
import 'vant/lib/icon/local.css'
import Vant from 'vant'

但是引入本地字体的时候会报错，如下：
error in ./node_modules/vant/lib/icon/local.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js:
ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/icon/vant-icon-872dd0.ttf' in .........
这会是什么原因造成的呢？

是用 vue-cli 3.0.1构建的项目
vant版本是 5.6.0

**Comment by chenjiahan** [comment]
vant 没有 5.6.0 版本，请升级到正确版本再试

**Comment by zlab** [comment]
@chenjiahan 1.4.4有这个问题，lib目录不存在

```js
import 'vant/lib/icon/local.css';
```
local.css
```css
@font-face {
  font-style: normal;
  font-weight: 400;
  font-family: vant-icon;
  src: url(../lib/icon/vant-icon-1ef3b9.ttf) format('truetype')
}
```
