### ISSUE TITLE
Icon本地字体报错

### ISSUE THREAD

**Issue by zlab** [youzan/vant#2113]
vant 1.4.4, lib目录不存在

```
This relative module was not found:

* ../lib/icon/vant-icon-1ef3b9.ttf in ./node_modules/css-loader
```

```js
import 'vant/lib/icon/local.css';
```
local.css
```css
@font-face {
  font-style: normal;
  font-weight: 400;
  font-family: vant-icon;
  src: url(../lib/icon/vant-icon-1ef3b9.ttf) format('truetype')
}
```
