### ISSUE TITLE
line style 的 tab 嵌套在 card style 的 tab 中，高度异常

### ISSUE THREAD

**Issue by hustlzp** [youzan/vant#2815]
**Describe the bug**

line style 的 tab 嵌套在 card style 的 tab 中，前者的高度规则 44px 会被后者的高度规则 30px 覆盖。

**Screenshots**

<img width="1249" alt="2019-02-21 10 58 38" src="https://user-images.githubusercontent.com/1180240/53140504-da600280-35c7-11e9-91ee-c30622a1d8a2.png">

**Environment**
 - Device: Chrome
 - Browser: Chrome
 - Vant Version: 1.6.5

**Solution**

使用 CSS 的直接子元素语法 `>`：

```css
.van-tabs--card > .van-tabs__wrap {
    height: 30px;
}
```

替换：

```css
.van-tabs--card .van-tabs__wrap {
    height: 30px;
}
```
