### ISSUE TITLE
search 组件 样式错误

### ISSUE THREAD

**Issue by YYQ8023** [youzan/vant#311]
### 试过两种css的引入方式包括：
1，在main.js里 import
2，在index.html里link(css文件从lib中复制)。
### 结果：
![image](https://user-images.githubusercontent.com/22813922/32773272-960f4db0-c963-11e7-88f8-d2cb059402c9.png)

**Comment by chenjiahan** [comment]
@YYQ8023 感谢反馈，将在下个版本修复，你可以通过设置下面的样式临时解决下

```css
.van-search__input-wrap {
  box-sizing: border-box;
}
```
