### ISSUE TITLE
hairline如何隐藏？

### ISSUE THREAD

**Issue by xiaoming0827** [youzan/vant#3316]
**Describe the bug**
vant组件默认都有hairline显示，这导致引入的组件都用边框效果，但是目前需求是不显示hairline，请问如何隐藏某个组件的hairline，谢谢！

**Screenshots**
没有截图，详细描述如上。

**Environment**
 - Device: pc
 - Browser: chrome手机模拟器
 - Vant Version: v.1.6.18

目前是不知道如何优雅的隐藏hairline，多谢百忙之中回复，十分感谢！

**Comment by chenjiahan** [comment]
添加下面的样式即可

```css
.van-cell::after,
[class*='van-hairline']::after {
  display: none;
}
```
