### ISSUE TITLE
android下van-tags边框1px的问题

### ISSUE THREAD

**Issue by CallMeHunter** [youzan/vant#3505]
IMPORTANT: Please use the following link to create a new issue. If your issue was not created using the app above, it will be closed immediately.

注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭。

**Describe the bug 描述问题**
android浏览器下, 设置了overflow:scroll容器内的元素足够滚动的时候, van-tags出现的1px边框显示不全的问题

**Screenshots 截图**
竖屏正常的效果:
![Screenshot_2019_0614_121653](https://user-images.githubusercontent.com/31719446/59483370-b3437e80-8e9f-11e9-9f65-23d35d26016c.jpg)
横屏放大后:
![Screenshot_2019_0614_121734](https://user-images.githubusercontent.com/31719446/59483372-b50d4200-8e9f-11e9-9fa8-4ff0d150ef63.jpg)

**Environment 环境**

 - Device: vivo z1
 - Browser:  微信内置浏览器
 - Vant Version:  ^2.0.0-beta.3

**Reproduce 复现步骤**
请使用 [codesandbox](https://codesandbox.io/s/m5v3f) 创建一个复现问题的示例，以帮助我们排查问题。

**Comment by CallMeHunter** [comment]
查了一些相关资料, 发现这样可以解决我的问题
就是不知道这样会不会还有其他什么副作用

```css
.van-tag--plain.van-hairline--surround {
    &::after{
      content: ' ';
      box-shadow: 0px 0px 0.01px 0.01px currentColor;
    }
  }
```
解决后的效果:
![Screenshot_2019_0614_121810](https://user-images.githubusercontent.com/31719446/59483526-68763680-8ea0-11e9-852d-cfdb7373559e.jpg)
