### ISSUE TITLE
用下面的代码,List触底刷新会无限的刷新,loading状态一直变为true

### ISSUE THREAD

**Issue by hzCat** [youzan/vant#3684]
### **直接用代码覆盖CLI 初始的helloworld组件**
```HTML
<template>
    <div class="game-board">
        <div class="act-detail" v-if='num.length>0'>
            <div class="infos">
                <div class="board">
                    <van-list @load="onload" v-model="loading" :finished="finish" :offset="100">
                        <ol>
                            <li v-for='(item,index) in num' :key='index'>{{item}}</li>
                        </ol>
                    </van-list>
                </div>
            </div>
        </div>
    </div>
</template>
```
```JavaScript
export default {
    data() {
        return {
            num: [],
            loading: false,
            finish: false
        };
    },
    created() {
        this.onload();
    },
    methods: {
        onload() {
            setTimeout(() => {
                let arr = [1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ];
                console.log("TCL: onload -> arr", arr);
                this.num = [...this.num, ...arr];
                this.loading = false;
                if (this.num.length >= 200) {
                    this.finish = true;
                }
            }, 3000);
        }
    }
};
```
```css
<style lang="scss" scoped >
@import "./detail.scss";
@import "./board.scss";

.game-board {
    padding: 33px 10px 0 10px;
}
.infos {
    padding: 20px;
    .title {
        padding: 0px 0px 14px;
        font-family: SourceHanSansCN-Bold;
        font-size: 17px;
        color: #fbe5ff;
    }
    .line {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        text-align: center;
        .left {
            width: 66px;
        }
        .center {
            width: 79px;
        }
        .right {
            width: 150px;
            text-align: center;
        }
    }
    .van-list {
        /deep/ .van-list__loading {
            width: 100%;
            text-align: center;
            font-family: SourceHanSansCN-Regular;
            font-size: 12px;
            color: #71669a;
        }
        /deep/ .van-list__finished-text {
            width: 100%;
            text-align: center;
            font-family: SourceHanSansCN-Regular;
            font-size: 12px;
            color: #71669a;
        }
    }
}
.loadings {
    width: 100%;
    text-align: center;
    font-family: SourceHanSansCN-Regular;
    font-size: 12px;
    color: #71669a;
    line-height: 50px;
}
</style>
```
> board.scss
```css
.board {
    border: 1px solid #00e5f0;
    box-shadow: 0 0 3px 0 rgba(0, 229, 240, 0.5), inset 0 0 1px 0 #490b9f;
    position: relative;

    &::before {
        content: " ";
        position: absolute;
        top: 0;
        left: 0;
        width: 10px;
        height: 10px;
        z-index: 1;
        background: #490b9f;
        border-bottom: 1px solid #00e5f0;
        transform: rotateZ(-45deg) translate(0.5px, -8.5px);
    }

    &::after {
        content: " ";
        position: absolute;
        bottom: 0;
        right: 0;
        width: 9px;
        height: 10px;
        z-index: 1;
        background: #490b9f;
        border-top: 1px solid #00e5f0;
        transform: rotateZ(-45deg) translate(-0.5px, 8.5px);
    }

    .triangle {
        position: absolute;
        left: 0;
        top: 0;
        border: 0 !important;
        min-height: 0 !important;
        line-height: 0 !important;
        padding: 0 !important;

        .right {
            text-align: center;
            line-height: 0 !important;
        }

        .arrow {
            display: inline-block;
            margin: 0 auto;
            width: 6px;
            height: 6px;
            border-top: 3px solid #00e5f0;
            border-left: 3px solid #00e5f0;
            border-bottom: 3px solid transparent;
            border-right: 3px solid transparent;
            transform: rotateZ(45deg);
            position: relative;
            top: -4px;
        }
    }

    .line {
        min-height: 41.5px;
        padding: 10px 0px;

        &:not(:last-child) {
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-image: linear-gradient(to right,
                    rgba(0, 229, 240, 0.1) 0%,
                    #00e5f0 50%,
                    rgba(0, 229, 240, 0.1) 100%);
            border-image-slice: 10;
            // border-top: 0;
            // border-left: 0;
            // border-right: 0;
        }
    }

    .left {
        width: 66px;
        display: flex;
        justify-content: center;
        align-items: center;

        img {
            width: 28px;
            display: inline-block;
        }
    }

    .center {
        font-family: PingFang-SC-Medium;
        font-size: 12px;
        color: #ffffff;
        text-align: center;
    }

    .right {
        font-family: PingFangSC-Regular;
        font-size: 12px;
        color: #dcd1ff;
        line-height: 15px;
        padding: 0 23px;
        text-align: left;
    }
}
```

> detail.css
```css
.act-detail {
    border-radius: 4px;
    width: 335px;
    margin-left: 15px;
    margin-top: 25px;
    position: relative;
    &::after {
        content: " ";
        width: 329px;
        position: absolute;
        top: 10px;
        left: 16px;
        bottom: 10px;
        background: #33b8d7;
        border-radius: 4px;
        z-index: 0;
    }

    .infos {
        background: #490b9f;
        border-radius: 4px;
        width: 335px;
        position: relative;
        z-index: 1;
        font-family: SourceHanSansCN-Regular;
        font-size: 14px;
        color: #dcd1ff;
        line-height: 20px;
        padding: 30px 20px;
        text-align: left;
        overflow-x: auto;
    }
}

```
