### ISSUE TITLE
[Bug Report] dialog内容框文字模糊

### ISSUE THREAD

**Issue by VisonM** [youzan/vant#3746]
### 设备 / 浏览器
chrome 

### Vant 版本
2.0.5

### Vue版本
2.6.10

### 重现链接
<a href="https://me.xyh.io/product/detail?id=SSENSE191387M214002" target="_blank">https://me.xyh.io/product/detail?id=SSENSE191387M214002</a>

### 描述问题
dialog使用transform:translate3d(-50%,-50%,0)定位，有可能是小数，导致文字模糊

**Comment by chenjiahan** [comment]
具体是什么系统的浏览器会出现呢，可以加这个样式试下，有效的话我们会加入到组件库内

```css
.van-dialog {
  -webkit-font-smoothing: subpixel-antialiased;
}
```
