### ISSUE TITLE
[Bug Report] NumberKeyboard组件v2.1.4版本自定义键盘样式显示有问题

### ISSUE THREAD

**Issue by Thlq** [youzan/vant#4181]
### 设备 / 浏览器
ios

### Vant 版本
2.1.4

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/number-keyboard" target="_blank">https://youzan.github.io/vant/#/zh-CN/number-keyboard</a>

### 描述问题
自定义键盘删除按钮有蓝色的border，显示异常
![image](https://user-images.githubusercontent.com/21211777/63431942-a2405c00-c452-11e9-8ce4-39a45d824a9f.png)

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复此问题

**Comment by chenjiahan** [comment]
这个问题可以临时添加一行样式解决一下，明天会发个修复版本

```css
/* fix hairline style for vant@2.1.4 */
.van-hairline {
  position: relative;
}
```
