### ISSUE TITLE
自定义tabbar选中颜色

### ISSUE THREAD

**Issue by github-gage** [youzan/vant#428]
请问如何自定义tabbar选中的颜色，谢谢

**Comment by chenjiahan** [comment]
@github-gage 目前需要通过覆盖样式的方式完成

```css
.van-tabbar-item--active {
    color: red;
}
```
