### ISSUE TITLE
[Bug Report] transition 导致特定情况下 list 组件初始无法触发加载

### ISSUE THREAD

**Issue by kid1412621** [youzan/vant#4294]
### 设备 / 浏览器
任意

### Vant 版本
2.1.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/embed/vant-issue-moban-l9y3q" target="_blank">https://codesandbox.io/embed/vant-issue-moban-l9y3q</a>

### 描述问题
demo 下来回切换 foo ， bar Tab

**Comment by chenjiahan** [comment]
@ystarlongzi 有空帮忙看下~

**Comment by ystarlongzi** [comment]
嗯嗯，好的，今天我看下

**Comment by ystarlongzi** [comment]
这个问题还是由于切换后 `<van-list />` 在可视区域外，因此导致不会触发 onLoad 事件

- 问：为什么快速的在 Foo 和 Bar 页面之间切换时，有时候触发 onLoad 呢？

- 答：首先，需要注意的一个点是：页面在左右切换时，它们的 UI 排列布局是「上下」的，而不是「左右」的。假设当前页面是 Foo，然后快速点击 Bar --> Foo --> Bar 时，切换大致过程如下：
  - Bar：此时由于 Foo 是一屏高，因此 Bar 是屏幕区域外，不会触发 onLoad
  
  - Foo：由于上次 Bar 未加载内容，因此高度是 0，所以此次 Foo 是在可视区域内，会触发 onLoad，开始加载数据
  
  - Bar：如果速度够快，切换会早于上次 Foo 加载数据完成前，此时 Foo 的高度也可认为是 0，所以这次 Bar 也是在可视区域内，所以会触发 onLoad


可以在 Layout.vue 里添加以下样式，延迟页面切换动画，然后观察这个过程

``` css
.van-slide-left-enter-active {
  animation-duration: 10s;
}
.van-slide-left-leave-active {
  animation-duration: 10s;
}
```

解决方案是：
 1. 切换时使用 `this.$refs.list.check();` 手动触发，或
 2. 保证页面切换时，布局是左右的，而不是上下的
