### ISSUE TITLE
How to set the label to be on top of Field

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4476]
The current label can be set to the left part of the field. How can I set it to be just above the field and not on the left?

**Comment by chenjiahan** [comment]
```html
<van-field label="Label" class="custom-field" />
```

```css
.custom-field {
  flex-direction: column;
}
```
