### ISSUE TITLE
On RadioGroup, how do I align the radio buttons to be horizontal and not vertical?

### ISSUE THREAD

**Issue by Mashiane** [youzan/vant#4509]
Hi there, how can I align the radios to be horizontal and not vertical in the radio group?

Thanks

**Comment by chenjiahan** [comment]
```css
.van-radio {
  display: inline-flex;
  margin-right: 10px;
}
```
