### ISSUE TITLE
[Bug Report] swipe组件配合路由动画无法正常显示

### ISSUE THREAD

**Issue by aaja** [youzan/vant#4746]
### 设备 / 浏览器
chrome

### Vant 版本
2.2.7

### Vue版本
2.6.10

### 重现链接
<a href="https://w9dx8.csb.app/#/swipe" target="_blank">https://w9dx8.csb.app/#/swipe</a>

### 描述问题
 $route(to, from) {
      if (to.meta.index > from.meta.index) {
        //设置动画名称
        this.transitionName = "app-slide-left";
      } else {
        this.transitionName = "app-slide-right";
      }
    }

去掉动画则可以正常显示；

**Comment by chenjiahan** [comment]
动画样式写的有问题，导致元素在动画过程中的宽高为 0，获取不到正确宽度。

加两行样式可解决：

```css
.app-slide-right-enter-active,
.app-slide-right-leave-active,
.app-slide-left-enter-active,
.app-slide-left-leave-active {
  left: 0;
  right: 0;
}
```
