### ISSUE TITLE
tab标签栏如何修改active时的颜色的

### ISSUE THREAD

**Issue by donxbei** [youzan/vant#499]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

TAB标签栏如何自定义颜色，看见文档没有写

**Comment by chenjiahan** [comment]
@donxbei 直接通过 css 覆盖样式即可

**Comment by donxbei** [comment]
谢谢

**Comment by chenjiahan** [comment]
客气~

**Comment by Jancat** [comment]
@chenjiahan @donxbei 在 `scoped style` 中是无法自定义 CSS 样式覆盖 `vant` 吗？
```scss
// scoped 必须要去掉？
<style scoped>
.van-tabs__line {
  background-color: blue;
}
</style>
```
