### ISSUE TITLE
vw布局中，van-tag组件样式会有bug或者需要兼容处理

### ISSUE THREAD

**Issue by imruxin** [youzan/vant#5209]
使用vw布局，并启用了Profill后，发现跟利用伪元素有关的样式都会受到影响，比如tag组件。
效果如下所示：

![image](https://user-images.githubusercontent.com/5736012/70306218-35a26f00-1841-11ea-8e48-158c49010c20.png)

其中收到影响是就是content这个属性值，需要而外设置一下content值，比如为空也可以。在我设置了

```css
.van-tag--round, .van-tag--round:after {
  content: "";
}
```

后，样式可以恢复正常，效果如下：

![image](https://user-images.githubusercontent.com/5736012/70306346-9a5dc980-1841-11ea-8c39-8bf7ea100a05.png)
