### ISSUE TITLE
[Bug Report] IndexBar 和 IndexAnchor  组件在 ActionSheet 组件内的问题

### ISSUE THREAD

**Issue by 1014156094** [youzan/vant#5453]
### 设备 / 浏览器
所有

### Vant 版本
2.4.0

### Vue版本
2.6.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-zgt43" target="_blank">https://codesandbox.io/s/vant-issue-moban-zgt43</a>

### 描述问题
当 ActionSheet 组件 round 设置为 false 时，IndexAnchor 组件索引会超出弹窗，注意滚动观察~

**Comment by chenjiahan** [comment]
这个是布局方式的问题，应该把滚动区域限制为 IndexBar 的内容区域，比如添加以下样式：

```css
.van-index-bar {
  height: 80vh;
  overflow: auto;
}

.van-action-sheet__header {
  z-index: 3;
  background-color: #fff;
}
```
