### ISSUE TITLE
[Feature Request] Collapse 折叠面板的一些问题

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5510]
### 这个功能解决了什么问题
Collapse 折叠面板 每一项 的 四周的圆角 8px怎么实现 点击前 和点击后 都是圆角 而且 .van-cell 和van-collapse-item__content 之间 是没有空隙的

### 描述您想要的解决方案
Collapse 折叠面板 每一项 的 四周的圆角 8px怎么实现 点击前 和点击后 都是圆角 而且 .van-cell 和van-collapse-item__content 之间 是没有空隙的    我需要实现这个样子

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
空隙指的是 border 吗，可以设置 `:border="false"`，圆角请自行用 css 实现

**Comment by W-ChenAMG** [comment]
css   圆角    只能分别单独实现  .van-cell    和  an-collapse-item__content     我需要  van-collapse-item   这个整个 都是圆角，而且展开以后 也是圆角        现在只能做到     单独设置圆角

**Comment by W-ChenAMG** [comment]
有解决方案吗？ 或者有什么办法  我给你截图看看

**Comment by chenjiahan** [comment]
```css
.van-collapse-item__title {
  border-radius: 8px;
}

.van-collapse-item__title--expanded {
  border-radius: 8px 8px 0 0;
}

.van-collapse-item__content {
  border-radius: 0 0 8px 8px;
}
```
