### ISSUE TITLE
[Feature Request] Collapse 折叠面板  关于圆角的一些问题

### ISSUE THREAD

**Issue by W-ChenAMG** [youzan/vant#5517]
### 这个功能解决了什么问题
css 圆角 只能分别单独实现 .van-cell 和 an-collapse-item__content 我需要 van-collapse-item 这个整个 都是圆角，而且展开以后 也是圆角 现在只能做到 单独设置圆角

### 描述您想要的解决方案
css 圆角 只能分别单独实现 .van-cell 和 an-collapse-item__content 我需要 van-collapse-item 这个整个 都是圆角，而且展开前和展开以后 都显示是圆角 现在只能做到 单独设置圆角   

### 建议的API是什么样的
无

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant/issues/5510

**Comment by W-ChenAMG** [comment]
这样子做  在点击的时候  明显可以看到  直角和圆角在闪    有什么解决办法吗?    或者我看到  有的折叠面板是    点击下  就相当于把点击的那个  面板 向下撑开一样   那种感觉        你可以看下饿了么 组件的那种效果    我不知道在哪里改

**Comment by chenjiahan** [comment]
```css
.van-collapse-item {
    border-radius: 8px;
    overflow: hidden;
}
```
