### ISSUE TITLE
[Bug Report] 有什么办法修改NavBar的边框颜色么?

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#5610]
### 设备 / 浏览器
IOS

### Vant 版本
2.4.3

### Vue 版本
2.6.11

### 重现链接
无

### 描述问题
想修改NavBar的边框颜色,但是好像无法修改???

**Comment by chenjiahan** [comment]
hairline 是伪元素实现的，用 after 选择器可以选中

```css
.van-nav-bar::after {
  border-color: red;
}
```
