### ISSUE TITLE
NavBar 导航栏点击左右两侧文字背景色怎么去掉呢

### ISSUE THREAD

**Issue by Davisjy** [youzan/vant#5619]
官方文档即可查看，长按两侧按钮，背景色会显灰，暂时没有看到哪里有样式覆写，感谢

https://youzan.github.io/vant/#/zh-CN/nav-bar#dai-ma-yan-shi

**Comment by chenjiahan** [comment]
可以通过 active 选择器覆写

```css
.van-nav-bar__text:active {
    background-color: #fff;
}
```

**Comment by vampcheah** [comment]
试过 .van-nav-bar__text:active 并无效果。点击时候，字体依然会变灰。
试过用 text-shadow, opacity 或者 active hover 等等都无效。
只要是同一区，例如 left，只要点击一个文字，全部字体和颜色都会一同变化。

https://youzan.github.io/vant/#/zh-CN/nav-bar#dai-ma-yan-shi

**Comment by chenjiahan** [comment]
@vampcheah 覆盖方式有变化

```css
.van-nav-bar__left:active,
.van-nav-bar__right:active {
    opacity: 1;
}
```
