### ISSUE TITLE
[Bug Report] 下拉刷新列表出现遮挡

### ISSUE THREAD

**Issue by powerdong** [youzan/vant#5878]
## 设备 / 浏览器
Chrome 浏览器

## Vant 版本
2.5.7

## Vue 版本
2.6.10

## 重现步骤

当只展示几项列表时下拉出现遮挡

详情查看图片
![8RsLi4.png](https://s1.ax1x.com/2020/03/21/8RsLi4.png)

**Comment by chenjiahan** [comment]
可以加一行样式来撑开容器的高度：

```css
.van-pull-refresh__track {
  min-height: 100vh;
}
```

下个版本会优化一下 track 的高度，跟父容器一致
