### ISSUE TITLE
Dialog message的字体大小无法修改。

### ISSUE THREAD

**Issue by jaycethanks** [youzan/vant#6074]
![image](https://user-images.githubusercontent.com/44388103/79467272-325d9200-8030-11ea-9913-f1258aefd837.png)

元素好像无法选中，不知道是不是写错了还是咋回事。有人帮我看看吗，多谢了！
css代码：
```CSS
.QueueStatus .vanDialog .van-dialog__content .van-dialog__message{
    font-size: 16px!important;
}
```
