### ISSUE TITLE
[Bug Report] nav-bar加padding-top后居中不对称

### ISSUE THREAD

**Issue by gp3098** [youzan/vant#6145]
### 设备 / 浏览器
mi5s

### Vant 版本
2.6.1

### Vue 版本
2.6.11

### 重现链接
<a href="https://codepen.io/gp3098/pen/NWGjLqE?editors=1111" target="_blank">https://codepen.io/gp3098/pen/NWGjLqE?editors=1111</a>

### 描述问题
在 navbar上增加padding-top:25px导致上下错乱，title加了padding;但是left
和right没有增加，居中不对齐

**Comment by chenjiahan** [comment]
下个版本会调整下样式，适配这种场景

**Comment by chenjiahan** [comment]
已在 2.7.0 版本修复

**Comment by chenjiahan** [comment]
2.7.0 的改动有问题，先 revert 了，加 padding 可以通过以下方法：

```css
.van-nav-bar {
  padding-top: 25px;
}
.van-nav-bar__left,
.van-nav-bar__right {
  top: 25px;
}
```
