### ISSUE TITLE
[Bug Report] card组件中图片显示不对

### ISSUE THREAD

**Issue by SimongLin** [youzan/vant#6230]
### 设备 / 浏览器
安卓 4.1-4.3 内置 webview

### Vant 版本
2.7.1

### Vue 版本
2.5.2

### 重现链接
<a href="https://codepen.io/simonglin/pen/PoPQPYB" target="_blank">https://codepen.io/simonglin/pen/PoPQPYB</a>

### 描述问题
card组件中图片全屏且拉伸显示了，感觉是img标签外部div宽高没能起到作用

![image](https://user-images.githubusercontent.com/33407631/81272154-b0391a00-907f-11ea-8739-26a616c4eddc.png)
![image](https://user-images.githubusercontent.com/33407631/81272226-cd6de880-907f-11ea-8fac-1c7ea0d1d3bb.png)

**Comment by chenjiahan** [comment]
可以添加以下样式试下是否有效：

```css
.van-card__thumb {
  -webkit-flex-shrink: 0;
  flex-shrink: 0;
}
```

**Comment by SimongLin** [comment]
> 可以添加以下样式试下是否有效：
> 
> ```css
> .van-card__thumb {
>   -webkit-flex-shrink: 0;
>   flex-shrink: 0;
> }
> ```

谢谢回答！
加上了，但是还是不可以

**Comment by chenjiahan** [comment]
可以检查下 autoprefixer 配置是否正确，flex 布局需要 autoprefixer 补全旧语法的

**Comment by SimongLin** [comment]
配置了的，我自己写了一个 div 测试，发现可以自动补全
autoprefixer({
        browsers: [
          "Android >= 4.1",
          "iOS >= 8",
          "Chrome > 31", 
          "ff > 31"
        ]
      }),

![image](https://user-images.githubusercontent.com/33407631/81533884-965a4880-9399-11ea-8315-cd40470c3ff1.png)

**Comment by chenjiahan** [comment]
实在不行就试试这样的写法：

```css
.van-card__thumb {
  min-width: 88px;
  max-width: 88px;
  min-height: 88px;
  max-height: 88px;
}
```
