### ISSUE TITLE
[Bug Report] GoodsAction组件中只有一个按钮时，不能正确显示圆角

### ISSUE THREAD

**Issue by herock** [youzan/vant#6342]
### 设备 / 浏览器
微信浏览器

### Vant 版本
2.8.3

### Vue 版本
2.6.1

### 重现链接
<a href="https://s1.ax1x.com/2020/05/23/YjuRiD.md.png" target="_blank">https://s1.ax1x.com/2020/05/23/YjuRiD.md.png</a>

### 描述问题
GoodsAction组件内，如果van-goods-action-button数量为1，则该按钮不能正确显示为圆角，具体而言，是左上角和左下角错误显示为方角。

**Comment by chenjiahan** [comment]
下个版本会修复，可以通过覆盖样式的方式临时解决一下：

```css
.van-goods-action-button--first.van-goods-action-button--last {
  border-radius: 999px;
}
```
