### ISSUE TITLE
[Bug Report] toast

### ISSUE THREAD

**Issue by lihaotian0607** [youzan/vant#6385]
### 设备 / 浏览器
mac/火狐浏览器

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 描述问题
在电脑火狐浏览器toast长文字会出现换行,而且字不多 在chrome浏览器没问题 真机上火狐浏览器没问题!

![image](https://user-images.githubusercontent.com/32523475/82920826-63739f80-9faa-11ea-9236-1d0b2f57b5b4.png)

**Comment by chenjiahan** [comment]
PC 火狐浏览器不在我们的适配范围内的。

可以单独加下面的样式试下：

```css
.van-toast--text {
  width: -moz-fit-content;
}
```
