### ISSUE TITLE
van-pull-refresh 组件的使用，包含列表时，任意位置下拉均触发刷新。

### ISSUE THREAD

**Issue by jaycethanks** [youzan/vant#6432]
> codesandbox 复现有点难受，我直接贴这里了，如有需要麻烦call我开穿透远程访问。一上午卡这里还没搞定好难受 -_-|||

### van-pull-refresh 组件的使用，包含列表时，任意位置下拉均触发刷新。

![image](https://user-images.githubusercontent.com/44388103/83374075-199d1600-a3fd-11ea-9053-98bdc6339b37.png)

如上图示，拖动任意item，都会触发刷新，这导致无法正常的滚动。

##### 以下是相关的部分vue代码：

```vue
<van-pull-refresh  v-model="isLoading" @refresh="onRefresh">
    <van-empty v-if="ifShowEmptyPage" :description="EmptyPageContent" />
    <div v-if="!ifShowEmptyPage" class="QueuingListContainer">
        <div class="SwipeCellContainer">
            <transition-group name="flip-list" tag="p" style="margin:0">
                <van-swipe-cell :key="item.timenode" v-for="(item, index) in returnQueuingData">
                    <van-cell
                              :style="{
                                      background: returnQueuingData.indexOf(item)==0 ? HeadRowBackgroundColor:'',
                                      color: returnQueuingData.indexOf(item)==0 ? HeadRowFontColor:'',
                                      }"
                              @click="showPopup(item)"
                              :is-link="true"
                              :border="true"
                              center:true
                              :title="returnQueuingData.indexOf(item)==0 ? '当前': index"
                              :value="
                                      '姓名：' + item.name + '          ' + '车牌：' + item.licenseplate
                                      "
                              />
                    <template #right>
<!-- 首行显示完成，他行显示叫号 -->
<van-button
            v-if="returnQueuingData.indexOf(item) == 0"
            square
            @click="onComplete(item)"
            type="primary"
            text="完成"
            />
<van-button
            v-if="returnQueuingData.indexOf(item) != 0"
            square
            @click="callingTheNextOne(item)"
            type="danger"
            text="叫号"
            />
                    </template>
                </van-swipe-cell>
            </transition-group>
        </div>
    </div>
</van-pull-refresh>
```

##### 相关CSS代码：

```css
  /* 路由页 */
  .QueueManagement  .QueuingListContainer{
    height: calc(100vh - 96px);
    /* 这里是用100vh 减去顶部导航navbar的高度和底部tabswitcher的和， 剩下的就是中间的主内容区域的高度 */
    overflow: scroll;
  }
```

######  *全部路由页面代码：*

```vue
<template>
  <transition name="fade">
    <div class="QueueManagement">
      <van-nav-bar title="排队管理">
        <template #right>
          <van-button type="default" to="/MainApp/QueueManagement/QueueManagementSetting">
            <van-icon name="ellipsis" size="32" />
          </van-button>
        </template>
      </van-nav-bar>

      <van-pull-refresh  v-model="isLoading" @refresh="onRefresh">
        <van-empty v-if="ifShowEmptyPage" :description="EmptyPageContent" />
        <div v-if="!ifShowEmptyPage" class="QueuingListContainer">
          <div class="SwipeCellContainer">
            <transition-group name="flip-list" tag="p" style="margin:0">
              <van-swipe-cell :key="item.timenode" v-for="(item, index) in returnQueuingData">
                <van-cell
                  :style="{
                  background: returnQueuingData.indexOf(item)==0 ? HeadRowBackgroundColor:'',
                  color: returnQueuingData.indexOf(item)==0 ? HeadRowFontColor:'',
                  }"
                  @click="showPopup(item)"
                  :is-link="true"
                  :border="true"
                  center:true
                  :title="returnQueuingData.indexOf(item)==0 ? '当前': index"
                  :value="
                  '姓名：' + item.name + '          ' + '车牌：' + item.licenseplate
                "
                />
                <template #right>
                  <!-- 首行显示完成，他行显示叫号 -->
                  <van-button
                    v-if="returnQueuingData.indexOf(item) == 0"
                    square
                    @click="onComplete(item)"
                    type="primary"
                    text="完成"
                  />
                  <van-button
                    v-if="returnQueuingData.indexOf(item) != 0"
                    square
                    @click="callingTheNextOne(item)"
                    type="danger"
                    text="叫号"
                  />
                </template>
              </van-swipe-cell>
            </transition-group>
          </div>
        </div>
      </van-pull-refresh>

      <van-popup v-model="showDetails" position="bottom" :style="{ width: '100%', height: '40%' }">
        <div class="RunnerInfo">
          <span>详细信息</span>
        </div>
        <van-cell-group>
          <van-cell class="pop_cell" :border="false" title="姓名" :value="PopContainer.Name_value" />
          <van-cell
            class="pop_cell"
            :border="false"
            title="车牌"
            :value="PopContainer.LicensePlate_value"
          />
          <van-cell
            class="pop_cell pop_cell_callPhone"
            :border="false"
            clickable
            @click="callPhone"
            title="手机"
            :value="PopContainer.PhoneNumber_value"
          />
          <van-cell
            class="pop_cell"
            :border="false"
            title="加入时间点"
            :value="PopContainer.JoinTimeNode_value"
          />
          <van-cell
            class="pop_cell"
            :border="false"
            title="等待时长"
            :value="PopContainer.WaitTimeDelta_value"
          />
        </van-cell-group>
      </van-popup>
    </div>
  </transition>
</template>
<script>
import { Notify, Toast, Dialog } from "vant";
import RequestApiList from "@/utils/RequestApiList.js";
export default {
  data() {
    return {
      HeadRowData: [
        //首行数据接收容器变量（首行和以第二行开始的行是两个数组，后者是服务端返回的全部队列数据去掉首行，前者就是取全部数据的索引为0的数据对象）
        {
          factory: "",
          licenseplate: "",
          name: "",
          passtimenode: "",
          phonenumber: "",
          queuing_id: "",
          status: "",
          timenode: ""
        }
      ],
      HeadRowFontColor: "#366c00",
      HeadRowBackgroundColor: "#d5ffcb",
      HeadRowTitle: "当前",
      showDetails: false,

      returnQueuingData: "", //自第二行开始全部队列数据的接受变量，有可能就是原始返回数据，有可能去除了索引为0的数据
      //pop展示运输员详细信息
      PopContainer: {
        Name_value: "",
        LicensePlate_value: "",
        PhoneNumber_value: "",
        JoinTimeNode_value: "",
        WaitTimeDelta_value: ""
      },
      isLoading: false, //刷新过渡
      ifShowEmptyPage: true,
      EmptyPageContent: "请下拉以刷新！"
    };
  },
  beforeMount() {
    this.onRefresh();
  },
  methods: {
    PullDownToRefreshCurrentQueuingListData() {
      if (this.$store.state.onLogin == true) {
        this.$axios
          .get(RequestApiList.HOST + RequestApiList.queuingdata.url_address, {
            params: {
              factory: this.$store.state.Factory
            }
          })
          .then(response => {
            let reg = /<.*?>/gi;
            let returnResult = response.data.replace(reg, "");
            let result = JSON.parse(returnResult);
            console.log(result);

            if (result.returnQueuingData.length == 0) {
              this.EmptyPageContent =
                "当前无排队车辆，请先通过申请列表中的入队申请。";
              this.ifShowEmptyPage = true;
              Notify({ type: "warning", message: "当前暂无排队！" });
            } else {
              //有返回数据 + 首行有数据
              this.returnQueuingData = result.returnQueuingData;
              // Notify({ type: "success", message: "获取队列数据成功！" });
            }
          })
          .catch(err => {
            console.error(
              "This is from QueueManagement/Func:PullDownToRefreshCurrentQueuingListData()\n",
              err,
              "\nConsole by Jayce !!!"
            );
            Notify({
              type: "danger",
              message: "获取队列数据失败，请尝试重新刷新！"
            });
          });
      } else {
        Toast.fail("请先登录！");
        return;
      }
    },
    showPopup(item) {
      this.PopContainer.JoinTimeNode_value = this.$moment(
        parseInt(item.timenode)
      ).format("YYYY MMMM Do,a h:mm:ss ");
      this.PopContainer.Name_value = item.name;
      this.PopContainer.LicensePlate_value = item.licenseplate;
      this.PopContainer.PhoneNumber_value = item.phonenumber;
      this.showDetails = true;

      let TimeDelta = this.$moment(new Date()).diff(
        parseInt(item.timenode),
        "minute"
      ); //to minute time delta;
      let TimeDelta_hour = Math.floor(TimeDelta / 60); //hours delta;
      let TimeDelta_minute = TimeDelta % 60;
      this.PopContainer.WaitTimeDelta_value =
        TimeDelta_hour + "小时" + TimeDelta_minute + "分钟";
    },
    onRefresh() {
      this.ifShowEmptyPage = false;
      this.PullDownToRefreshCurrentQueuingListData();
      this.isLoading = false;
    },
    callingTheNextOne(item) {
      console.log("callingTheNextOne():", item);
      if (this.$store.state.onLogin == true) {
        this.$axios
          .get(
            RequestApiList.HOST + RequestApiList.calling_thenextone.url_address,
            {
              params: {
                Factory: item.factory,
                PhoneNumber: item.phonenumber
              }
            }
          )
          .then(response => {
            let reg = /<.*?>/gi;
            let returnResult = response.data.replace(reg, "");
            let result = JSON.parse(returnResult);
            if (result.status == 3.7) {
              Notify({
                type: "danger",
                message: "当前有正在处理的车辆，请先处理后再试！"
              });
            } else {
              let middleValue = item;
              this.returnQueuingData.splice(
                this.returnQueuingData.indexOf(item)
              );
              this.returnQueuingData.unshift(middleValue);
              // this.onRefresh();
            }
            this.onRefresh();
          })
          .catch(err => {
            console.error(
              "This is from QueueManagement/Func:callingTheNextOne()\n",
              err,
              "\nConsole by Jayce !!!"
            );
            Notify({
              type: "danger",
              message: "获取队列数据失败，请尝试重新刷新！"
            });
          });
      } else {
        Toast.fail("请先登录！");
        return;
      }
    },
    callPhone() {
      //点击详情弹窗的手机号码可以直接拨号
      window.location.href = "tel://" + this.PhoneNumber_value;
    },
    onComplete(item) {
      //首行功能，是否完成
      Dialog.confirm({
        // title: "标题",
        message: "确认完成？",
        className: "vanDialog"
      })
        .then(() => {
          // on confirm
          //加一个判断条件， 如果首行没有数据，就不不要发请求，否则会报错
          if (this.returnQueuingData[0].name == "") {
            Toast.fail("当前无正在卸货中的车辆！");
          } else {
            this.$axios
              .get(
                RequestApiList.HOST +
                  RequestApiList.complete_fromthequeuinglist.url_address,
                {
                  params: {
                    TimeNode: item.timenode,
                    User: item.phonenumber
                  }
                  // TimeNode: item.timenode,
                  // User:item.phonenumber
                }
              )
              .then(response => {
                let reg = /<.*?>/gi;
                let returnResult = response.data.replace(reg, "");
                let result = JSON.parse(returnResult);
                console.log(result);
                Toast.success("已确认！");
                this.returnQueuingData.splice(
                  this.returnQueuingData.indexOf(item),
                  1
                );
                this.onRefresh();
              })
              .catch(err => {
                console.error(
                  "Complete From QueuingList Failed,This is from QueueManagement.vue/Func:onComplete()\n",
                  err,
                  "\nConsole by jayce !!!"
                );
              });
            // on confirm
          }
        })

        .catch(() => {
          // on cancel
        });
    }
  }
};
</script>
<style scoped>
.RunnerInfo {
  display: flex;
  justify-content: center;
  align-items: center;
}

.flip-list-move {
  transition: transform 0.5s;
}
@import "~@/assets/css/components/MainApp/QueueManagement/QueueManagement.css";
@import "~@/assets/css/commonTransition.css";
</style>

```

###### *组件css*

```css
/* nav Bar */
.QueueManagement .van-nav-bar__right * {
    border: none;
}

.QueueManagement .van-nav-bar__right {
    padding: 0;
}

.QueueManagement .van-nav-bar__title {
    font-size: 18px;
    font-weight: 600;
}

/* 路由页 */
.QueueManagement .QueuingListContainer {
    height: calc(100vh - 96px);
    /* 这里是用100vh 减去顶部导航navbar的高度和底部tabswitcher的和， 剩下的就是中间的主内容区域的高度 */
    overflow: scroll;
}

.QueueManagement .van-cell__title {
    text-align: center;
    margin-right: 0.5em;
    font-size: 16px;
    flex: 1;
}

.QueueManagement .van-cell__value {
    white-space: pre;
    font-size: 16px;
    flex: 6;
}

.QueueManagement .van-cell {
    padding: 20px 16px;
}

.QueueManagement .van-swipe-cell .van-button {
    height: 100%;
}

.QueueManagement .van-cell__value {
    color: #000;
    text-align: left;
}

/* 弹出运输员详细信息的cell样式 */

.QueueManagement .pop_cell {
    padding: 8px 16px;
}

.QueueManagement .pop_cell .van-cell__title {
    text-align: left;
    flex: 2;
}

.QueueManagement .pop_cell .van-cell__value {
    flex: 5;
}

.QueueManagement .van-popup--bottom {
    height: 250px !important;
}

.QueueManagement .RunnerInfo {
    margin: 2%;
}

.QueueManagement .RunnerInfo span {
    font-size: 16px;
    font-weight: 600;
}

/*手机号样式*/
.QueueManagement .pop_cell_callPhone .van-cell__value span {
    color: #2c6b9c;
    text-decoration: underline;
}
```

**Comment by jaycethanks** [comment]
### 我做过这样的尝试：

给`<van-pull-refresh>`组件加上`overflow: scroll;`样式，并去除渲染列表元素的`overflow: scroll;`样式。

```vue
      <van-pull-refresh style="overflow: scroll;"  v-model="isLoading" @refresh="onRefresh">
        ···
       </van-pull-refresh>
```

注释掉渲染表的 overflow: scroll; 样式
```css
.QueueManagement .QueuingListContainer {
    height: calc(100vh - 96px);
    /* overflow: scroll; */
}
```

### 会出现这种奇怪的问题：
![image](https://user-images.githubusercontent.com/44388103/83380240-0c3d5700-a410-11ea-8061-52ff75d99d1b.png)
（nav bar 没有了，且时不时还是出现最初的任意item拖动，触发刷新的问题，我没有调试出来
具体是怎么触发的。）

**Comment by chenjiahan** [comment]
只要滚动条在顶部就可以触发下拉刷新。

你将列表内容设置为了局部滚动，所以 PullRefresh 组件外部的滚动条永远处于顶部位置，因此能够触发下拉刷新。

建议你调整下布局，看起来没必要使用局部滚动。

**Comment by jaycethanks** [comment]
> 只要滚动条在顶部就可以触发下拉刷新。
> 
> 你将列表内容设置为了局部滚动，所以 PullRefresh 组件外部的滚动条永远处于顶部位置，因此能够触发下拉刷新。
> 
> 建议你调整下布局，看起来没必要使用局部滚动。

非常感谢，确实是这个原因导致了，按照你的建议解决了。  !thumbup

**Comment by jaycethanks** [comment]
目前，像这样修改后是正常的，下方代码供参考：
```vue
<div class="content">
<van-pull-refresh v-model="isLoading" @refresh="onRefresh">
  <van-empty
    v-if="ifShowEmptyPage"
    style="height: calc(100vh - 96px);"
    :description="BindDescription"
  />
  <div v-if="!ifShowEmptyPage" class="SwipeCellContainer_ApplyingList">
    <!-- transition列表渲染动画 -->
    <transition-group name="list" tag="p" style="margin:0">
      <van-swipe-cell :key="item.timenode" v-for="(item, index) in returnApplyingData">
        <van-cell
          @click="showPopup(item)"
          :is-link="true"
          :border="true"
          center:true
          :title="index"
          :value="
        '姓名：' + item.name + '          ' + '车牌：' + item.licenseplate
      "
        />
        <template #right>
          <van-button square @click="onAllowing(item)" type="primary" text="通过申请" />
        </template>
        <template #left>
          <van-button square @click="onDenying(item)" type="danger" text="驳回" />
        </template>
      </van-swipe-cell>
    </transition-group>
    <!--  -->
  </div>
</van-pull-refresh>
</div>
```

css,只是设定了.SwipeCellContainer_ApplyingList的overflow属性为scroll。  特别注意不要设定其他的height属性就好了。 
```css
  /* 路由页 */
  .AskForJoinTheQueue  .SwipeCellContainer_ApplyingList{
    /* height: calc(100vh - 96px); */
    /* 这里是用100vh 减去顶部导航navbar的高度和底部tabswitcher的和， 剩下的就是中间的主内容区域的高度 */
    overflow: scroll;
  }

.AskForJoinTheQueue .van-nav-bar__title{
  font-size: 18px;
  font-weight: 600;
}

.AskForJoinTheQueue .van-nav-bar__right *{
  padding: 0;
  border: none;
  background: transparent;
  display: flex;
  justify-content: center;
  align-items: center;
}

.AskForJoinTheQueue .RunnerInfo {
  display: flex;
  justify-content: center;
  align-items: center;
}

.AskForJoinTheQueue .van-cell__title {
  margin-right:0.5em;
  font-size: 16px;
  flex: 1;
}

.AskForJoinTheQueue .van-cell__value {
  white-space: pre;
  font-size: 16px;
  flex: 6;
}

.AskForJoinTheQueue .van-cell {
  padding: 20px 16px;
}
/* .AskForJoinTheQueue {
  overflow: scroll;
  height: auto;
} */

.AskForJoinTheQueue .van-swipe-cell__wrapper .van-cell__title{
  text-align: center;
}

.AskForJoinTheQueue .van-swipe-cell .van-button {
  height: 100%;
}

.AskForJoinTheQueue .van-cell__value {
  color: #000;
  text-align: left;
}

/* 弹出运输员详细信息的cell样式 */
.AskForJoinTheQueue .pop_cell {
  padding: 8px 16px;
}

.AskForJoinTheQueue .pop_cell .van-cell__title {
  flex: 2;
}

.AskForJoinTheQueue .pop_cell .van-cell__value {
  flex: 5;
}

.AskForJoinTheQueue .van-popup--bottom {
  height: 200px!important;
}

.AskForJoinTheQueue .RunnerInfo {
  margin: 2%;
}
.AskForJoinTheQueue .RunnerInfo span{
  font-size: 16px;
  font-weight: 600;
}

/*手机号样式*/
.AskForJoinTheQueue .pop_cell_callPhone .van-cell__value span{
  color:#2c6b9c;
  text-decoration: underline;
}
```
