### ISSUE TITLE
[Bug Report] uploader组件反填后数据不刷新

### ISSUE THREAD

**Issue by 1273082756** [youzan/vant#6806]
## 截图链接:
- 图1(https://sm.ms/image/7DfLOMhs2G395cY)
- 图2(https://sm.ms/image/eR73NVOv4qUnLk2)

## 复现链接
- https://codesandbox.io/s/floral-fast-v85c4?file=/src/components/HelloWorld.vue
- https://v85c4.csb.app/

## 复现环境:
- iPhone X(ios13.4.1) (Chrome 84.0.4147.71(无痕模式) && Safari),
## BUG说明:
在使用uploader组件的时候,我用v-model绑定了一个fileList的变量,该变量为一个数组,每个数组元素为一个对象 { url:'xxx',isImage: true },我在用户选中下拉菜单的项目后,加载对应项目的文件列表,我选择操作fileList变量来将文件反填到uploader组件上,该操作在安卓设备上(Chrome)表现正常,在iPhone X设备上(Chrome/Safari)上表现为如 ***图1*** 所示的图片不显示,我通过检查元素发现,图片的链接已经在 ***图2*** 所示的位置已经成功挂载到img标签的src属性上,并且在network下查看图片资源已经成功下载,随后我通过手动触发uploader组件刷新,该图片才正常显示

**Comment by chenjiahan** [comment]
看起来是你覆盖的样式触发了浏览器的渲染 bug，由下面这行导致：

```css
.van-uploader__preview-image {
  width: 100%;
}
```

改成下面这样既可：

```css
.van-uploader__preview,
.van-uploader__preview-image {
  width: 100%;
}
```
