### ISSUE TITLE
[Bug Report] input的disabled样式在safari颜色太浅看不清

### ISSUE THREAD

**Issue by DrebinPeng** [youzan/vant#7078]
### 设备 / 浏览器
iphone 8 plus; safari

### Vant 版本
2.9.4

### Vue 版本
2.6.12

### 重现链接
<a href="https://youzan.github.io/vant/#/zh-CN/" target="_blank">https://youzan.github.io/vant/#/zh-CN/</a>

### 描述问题
input输入框的文字在disabled状态下，颜色太浅看不清，原因如下：
```css
.van-field__control:disabled {
    color: #c8c9cc;
    background-color: transparent;
    cursor: not-allowed;
    opacity: 1;
    -webkit-text-fill-color: currentColor;
}
```
其中-webkit-text-fill-color: currentColor;在iphone 8 plus的safari中不生效，需要强制修改为如下才能正常显示

```css
.van-field__control:disabled {
    -webkit-text-fill-color: #c8c9cc;
    -webkit-opacity: 1 !important;
    opacity: 1 !important;
    color: #c8c9cc;
}
```
