### ISSUE TITLE
[Bug Report] Checkbox自定义图标显示异常

### ISSUE THREAD

**Issue by yuner523** [youzan/vant#7117]
### 设备 / 浏览器
chrom

### Vant 版本
2.10.4

### Vue 版本
2.5.2

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-3cloq?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-3cloq?file=/src/App.vue</a>

### 描述问题
Checkbox自定义图标时，使用van-icon作为新图标，图标依然显示复选框的小圆圈（小方圈）

**Comment by chenjiahan** [comment]
目前 Checkbox 里的 Icon 组件会应用 Checkbox 的图标样式，所以看到的效果是圆圈。

可以通过 css 覆盖一下

```css
.van-checkbox__icon .van-icon {
    color: red;
    border: none;
}
```
