### ISSUE TITLE
[Bug Report] van-list 组件下拉刷新和页面滚动冲突

### ISSUE THREAD

**Issue by albercy** [youzan/vant#7189]
### 设备 / 浏览器
ipad/safari

### Vant 版本
2.10.6

### Vue 版本
2.6.12

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-2r4br?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-2r4br?file=/src/App.vue</a>

### 描述问题
vant-list 组件开启下拉刷新后，在页面向上滚动时也会触发下拉刷新事件，导致滚动事件无法正常完成

**Comment by chenjiahan** [comment]
建议把这些样式去掉，或者把 PullRefresh 放在局部滚动容器的内部。否则会导致 PullRefresh 的触顶判定失效

```css
html,
body {
  height: 100%;
}
.list {
  height: calc(100vh - 15rem);
  overflow: auto;
}
```
