### ISSUE TITLE
stype scoped无法覆盖部分样式例如dialog的.van-dialog__cancel

### ISSUE THREAD

**Issue by junk123321** [youzan/vant#720]
使用了Dialog，要把取消按钮的文字改成“删除”，颜色改成红色，style不加scoped颜色没问题，加了无效。应该是scoped只能作用域根节点原因吧。这种细调应该是常见的。有没有什么办法实现？类似的还有Dialog的van-nav-bar__title。谢谢！

```css
<style scoped>
.van-dialog__cancel {
  color: red;
}
</style>
```
