### ISSUE TITLE
[Bug] 2.10.9版本  Popup弹窗，关闭按钮绝对定位失效

### ISSUE THREAD

**Issue by lehui521** [youzan/vant#7448]
不知道是不是bug，**Popup**组件提供的**closeable**属性，会显示一个关闭的icon图标
这个图标在**Popup**内容滚动的时候，也会跟着内容滚动，并不是定位在页面上
![ce61b3859a365628e9f6adefe22aa87](https://user-images.githubusercontent.com/34447721/97655848-f4423000-1aa0-11eb-9879-95ae5d4bd269.png)
![ca8b944731d7409a873508bd8fcd601](https://user-images.githubusercontent.com/34447721/97655923-2358a180-1aa1-11eb-80f6-cd470d0f2d1d.png)

**Comment by chenjiahan** [comment]
可以在内部加一层滚动容器来解决这个问题

```html
<van-popup
  v-model="show"
  class="popup"
  closeable
  position="bottom"
>
  <div class="popup-content">
    content
  </div>
</van-popup>
```

```css
.popup {
  display: flex;
  height: 30%;
}

.popup-content {
  flex: 1;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}
```
