### ISSUE TITLE
SwipeCell 描述可以进行换行吗？

### ISSUE THREAD

**Issue by li308870559** [youzan/vant#7480]
SwipeCell 描述可以进行换行吗？
![400](https://user-images.githubusercontent.com/46514939/97962200-9d658f00-1def-11eb-89a6-24f578528779.png)

**Comment by li308870559** [comment]
或者是否允许写多条desc

**Comment by chenjiahan** [comment]
可以通过覆盖样式来允许换行

```css
.van-card__desc {
    overflow: visible;
    white-space: pre-wrap;
}
```
