### ISSUE TITLE
van-field 如何修改错误提示文字颜色？

### ISSUE THREAD

**Issue by Rotor1996** [youzan/vant#7522]
![image](https://user-images.githubusercontent.com/36121210/98506769-36385680-2297-11eb-9b72-bcb3e67da9a6.png)
使用/deep/ .van-field--error 控制文字颜色无效

**Comment by chenjiahan** [comment]
需要使用这个选择器：

```css
.van-field--error--error .van-field__control {
  &,
  &::placeholder {
     color: #xxxxxx;
  }
}
```
