### ISSUE TITLE
[Feature Request] Sidebar侧边导航栏希望可以加颜色设定

### ISSUE THREAD

**Issue by lehui521** [youzan/vant#7567]
![32060dddb3195ddc61d736d7213e0ae](https://user-images.githubusercontent.com/34447721/99208165-b82a0180-27fa-11eb-9931-31bab062bc13.png)
目前只有一个红色的颜色，并且不能修改
后期希望可以加一下颜色设定的属性

**Comment by chenjiahan** [comment]
可以通过主题定制或者以下 css 修改：

```css
.van-sidebar-item--select::before {
  background-color: blue;
}
```
