### ISSUE TITLE
[Bug Report] Popover 组件在企业微信端下边线显示问题

### ISSUE THREAD

**Issue by lanten** [youzan/vant#7698]
在企业微信端（v3.0.36）出现的问题，Popover 弹出菜单的下边线发生异常位移。

如图所示：

![image](https://user-images.githubusercontent.com/16203518/101304680-d031f580-387b-11eb-9cb9-deee8141f804.png)

解决方案：
``` css
.van-popover__action {
  .van-hairline--bottom {
    height: inherit;
  }
}
```
