### ISSUE TITLE
[Bug Report] 部分地区 CDN 无法访问

### ISSUE THREAD

**Issue by xiaowei2019996** [youzan/vant#7987]
### 设备 / 浏览器
iOS/safori

### Vant 版本
3.0.5

### Vue 版本
3.0.5

### 重现链接
<a href="https://img.yzcdn.cn/vant/logo.png" target="_blank">https://img.yzcdn.cn/vant/logo.png</a>

### 描述问题
cdn失效导致图标均显示失败

**Comment by chenjiahan** [comment]
目前运营商限制，导致辽宁联通用户无法访问 img.yzcdn.cn 域名，正在处理

**Comment by dunkong** [comment]
> 目前由于运营商限制，导致辽宁联通用户无法访问 img.yzcdn.cn 域名，正在处理

合肥移动也不行

**Comment by chaorenluo** [comment]
深圳的也不行 cnd字体图加载失败

**Comment by chenjiahan** [comment]
还有哪些地区挂的嘛？大家可以反馈一下

**Comment by chenjiahan** [comment]
> 深圳的也不行 cnd字体图加载失败

字体图标加载失败的，可以升级到 Vant 2.10.13 以上版本（用的是 base64 图标）

**Comment by wangxy69** [comment]
合肥移动还是不行，麻烦再确认下呢

**Comment by dunkong** [comment]
> > 深圳的也不行 cnd字体图加载失败
> 
> 字体图标加载失败的，可以升级到 Vant 2.10.13 以上版本（用的是 base64 图标）

用的是小程序版，无法升级到此版本

**Comment by dunkong** [comment]
如果短时间类无法修复，可以把相关附件发上来，我们进行替换，目前来看凡是img.yzcdn.cn域名下的都无法加载，你们官网进去也是挂了一堆图片，区域：合肥移动，测试联通、电信正常

**Comment by chenjiahan** [comment]
可以把 img.yzcdn.cn 替换为 img01.yzcdn.cn（备用域名）

**Comment by chenjiahan** [comment]
添加以下代码，可以修复 iconfont 字体问题：

```css
@font-face {
  font-weight: normal;
  font-family: 'vant-icon-new';
  font-style: normal;
  font-display: auto;
  src: url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2') format('woff2'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff') format('woff'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.ttf') format('truetype');
}

.van-icon {
  font-family: 'vant-icon-new' !important;
}
```
