### ISSUE TITLE
[Bug Report] list在本地可正常下拉加载，正式不行

### ISSUE THREAD

**Issue by 444136347** [youzan/vant#8069]
### 设备 / 浏览器
chrome

### Vant 版本
2.12.3

### Vue 版本
2.5.2

### 重现链接
<a href="https://www.yourmao.com/#/me/draw" target="_blank">https://www.yourmao.com/#/me/draw</a>

### 描述问题
List组件在本地可正常下拉加载，正式不行。Sticky也是一样本地可吸顶，正式不行

**Comment by 444136347** [comment]
https://user-images.githubusercontent.com/22359201/106694500-af83e300-6613-11eb-829c-5e5bcdea878a.mp4

这个是我本地的操作视频

**Comment by chenjiahan** [comment]
删除以下样式即可

```css
body, html {
    width: 100%;
    height: 100%;
}
```
