### ISSUE TITLE
Radio与Cell组件一起使用时和示例的样式不一样，不知道时候需要手动重新设置样式？

### ISSUE THREAD

**Issue by wupuyi** [youzan/vant#811]
```html
<van-radio-group v-model="radio">
  <van-cell-group>
    <van-cell><van-radio name="1">单选框 1</van-radio></van-cell>
    <van-cell><van-radio name="2">单选框 2</van-radio></van-cell>
  </van-cell-group>
</van-radio-group>
```

![9x0AwF.png](https://s1.ax1x.com/2018/03/31/9x0AwF.png)

**Comment by cookfront** [comment]
demo为了展示效果添加了一些自定义样式，你可以添加以下自定义样式：

```css
.van-cell {
  .van-radio__input {
    float: right;
    position: static;
  }

  .van-radio__label {
    margin: 0;
  }
}
```
