### ISSUE TITLE
[Feature Request] van-nav-bar  van-search 组合  插槽 left right titel 能不能再增加一个 center  

### ISSUE THREAD

**Issue by Messilimeng** [youzan/vant#8414]
### 这个功能解决了什么问题
把van-search  放在 van-nav-bar 插槽中  van-search 无法撑满 bar，  能否加个center 让他平铺 在里面

### 描述您想要的解决方案
让 van-search平铺在里面 而不是显示一半

### 建议的API是什么样的
加个center

**Comment by Messilimeng** [comment]
![image](https://user-images.githubusercontent.com/12272166/112642861-b0502d00-8e7e-11eb-8a54-5e4580aa0621.png)

**Comment by chenjiahan** [comment]
覆盖 .van-nav-bar__title 的样式即可

```css
.van-nav-bar__title {
  max-width: none;
  width: 100%;
}
```
