### ISSUE TITLE
如何转换自定义适配px>rem

### ISSUE THREAD

**Issue by charmfocus** [youzan/vant#8467]
项目采用vw+rem自定义了大小适配:
设计稿按375来设计的,为了方便计算,100px=1rem,所以font-size=100/3.75=26.66666666vw
```css
html {
  font-size: 26.666666666666668vw
}
```
这样的话,之前 定义的14px,就改写为0.14rem;
但vant里都用的是px,用postcss适配,会导致已经适配正常的样式出现问题,原因是postcss会在html元素增加font-size:37.5px,其实我想要的是只需要把vant里所有的值xxx px 改为 0.xxx rem即可.
哪位大神能给出合理的方案

**Comment by JokerLoLgrey** [comment]
postcss.config.js, 你可以参考一下
![image](https://user-images.githubusercontent.com/33446705/113830646-6853d300-97b9-11eb-988f-a4d3197dbcfc.png)

**Comment by charmfocus** [comment]
> postcss.config.js, 你可以参考一下
> ![image](https://user-images.githubusercontent.com/33446705/113830646-6853d300-97b9-11eb-988f-a4d3197dbcfc.png)

这个我试了,解决不了问题,因为postcss会在html元素上添加font-size:37.5px,而我已经在全局样式中定义了:
```css
html {
font-size: 26.666666666666668vw
}
```
导致原来的项目适配好的样式被搞乱了,我只需要让postcss做vant样式里的单位转换 `xxx px -> 0.xxx rem` 即可,不需要让他再改html的样式
