### ISSUE TITLE
[Bug Report] Popup关闭按钮如何放置在内容之外

### ISSUE THREAD

**Issue by sliontc** [youzan/vant#8790]
### 设备 / 浏览器
小米CC9

### Vant 版本
3.0.17

### Vue 版本
3.0.11

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-forked-1ddjc" target="_blank">https://codesandbox.io/s/vant-issue-moban-forked-1ddjc</a>

### 描述问题
如何把关闭按钮放置在内容之外的下方，也就是放到遮罩层上，如下图：
![image](https://user-images.githubusercontent.com/6959147/120256688-4199b080-c2c1-11eb-9a9f-b777feadcab7.png)

**Comment by chenjiahan** [comment]
可以自行覆盖 CSS 样式喔

```css
.van-popup {
  overflow-y: visible;
}

.van-popup__close-icon {
  top: -100px;
}
```
