### ISSUE TITLE
[Feature Request] 如何自定义全局字体

### ISSUE THREAD

**Issue by techrex** [youzan/vant#8958]
### 这个功能解决了什么问题
如何自定义全局字体

### 描述您想要的解决方案
我使用ConfigProvider无法自定义body的字体

### 建议的API是什么样的
提供一个可以覆盖全局自定义样式的接口，例如ant-design-vue是在webpack中可以配置全局自定义样式

**Comment by chenjiahan** [comment]
直接覆盖 body 标签的字体就行

```css
body {
  font-family: 'xxx'
}
```
