### ISSUE TITLE
[Feature Request] Search组件的自定义按钮的点击样式

### ISSUE THREAD

**Issue by kaivenke** [youzan/vant#9624]
### 这个功能解决了什么问题
Search组件的自定义按钮的点击样式无法有效更改。
````html
<van-search
      v-model="searchValue"
      shape="round"
      background="linear-gradient(to right, #7f7fd5, #86a8e7, #91eae4)"
      placeholder="请输入搜索关键词"
      show-action
      @search="onSearch"
>
    <template #action>
            <div class="search-button" @click="onSearch">搜索</div>
    </template>
</van-search>
````
````css
.search-button:active{
background-color: #7f7fd5;
}
````
如此案例，设置了search的背景颜色后，自定义按钮的点击样式十分格格不入，而通过修改search-button的样式发现该按钮外层div两侧有个8px的padding造成样式有问题。

### 描述您想要的解决方案
希望给search的自定义按钮给个自定义样式的方案，或者将自定义按钮的外层div两侧的padding置0

### 建议的API是什么样的
给van-search组件增加一个action-click属性，用于设置自定义按钮的点击背景色，如action-click="#7f7fd5"

**Comment by kaivenke** [comment]
有大佬指导通过手动找到vant组件定义的外部div的class，然后手动重写它的样式：
````css
.van-search__action {
  padding: 0px;
}
````
这样就能覆盖掉原来左右两侧8px的padding，然后再设置自定义按钮的button样式即可。。。

233333，，，，曲线救国....

**Comment by kaivenke** [comment]
> 衍生出新问题，当Search组件，使用了插槽自定义按钮，并且按钮是圆角按钮的时候，这个时候点击按钮就会出现背景颜色。
> 原因是通过点击事件加了一个样式：
> ``` css
> .van-search__action:active {
>     background-color: #f2f3f5;
> }
> ```
> 
> 我尝试覆盖这个样式也无法解决


以下是我的做法，我这样使用避免了这个问题

按钮组件

```html
<template #action style="padding:0px"> 

<div class="search-button" @click="onSearch"> 

搜索 

</div> 

</template>


```
样式定义

```css
.search-button { 

border-radius: 20px; 

width: 3rem; 

color: #7f7fd5; 

text-align: center; 

} 

.search-button:active { 

color: white; 

}

```

**Comment by kaivenke** [comment]
> 衍生出新问题，当Search组件，使用了插槽自定义按钮，并且按钮是圆角按钮的时候，这个时候点击按钮就会出现背景颜色。
> 原因是通过点击事件加了一个样式：
> ``` css
> .van-search__action:active {
>     background-color: #f2f3f5;
> }
> ```
> 
> 我尝试覆盖这个样式也无法解决

@rehack 


以下是我的做法，我这样使用避免了这个问题

按钮组件
```html
<template #action style="padding:0px">
  <div class="search-button" @click="onSearch"> 
    搜索
   </div> 
</template> 
```
样式定义
```css
.search-button { 
  border-radius: 20px; 
  width: 3rem; color: #7f7fd5; 
  text-align: center; 
} 
.search-button:active { 
  color: white; 
}
```

**Comment by kaivenke** [comment]
> 衍生出新问题，当Search组件，使用了插槽自定义按钮，并且按钮是圆角按钮的时候，这个时候点击按钮就会出现背景颜色。
> 原因是通过点击事件加了一个样式：
> ``` css
> .van-search__action:active {
>     background-color: #f2f3f5;
> }
> ```
> 
> 我尝试覆盖这个样式也无法解决

@rehack 
因为这个地方我给整个search框设置了背景色，所以我给这个点击事件增加了search框的背景相同的颜色，实际上就是解决了我当时的需求，没有解决实际问题😥

**Comment by kaivenke** [comment]
> 衍生出新问题，当Search组件，使用了插槽自定义按钮，并且按钮是圆角按钮的时候，这个时候点击按钮就会出现背景颜色。
> 原因是通过点击事件加了一个样式：
> ``` css
> .van-search__action:active {
>     background-color: #f2f3f5;
> }
> ```
> 
> 我尝试覆盖这个样式也无法解决

@rehack 

最后我实际在上线的时候使用了如下代码示例，实现了将该按钮改为文字按钮，且点击后颜色发生变化
组件定义如下
```html
<template #action style="padding:0px"> 

<div class="search-button" @click="onSearch"> 

搜索 

</div> 

</template>

```

css如下

```css
.search-button { 

border-radius: 20px; 

width: 3rem; 

color: #7f7fd5; 

text-align: center; 

} 

.search-button:active { 

color: white; 

} 

.van-search__action { 

border-radius: 20px; 

margin-left: 2px; 

margin-right: 2px; 

background: transparent; 

padding: 0px; 

}

```

最终实现的效果为
未点击样式：
![IMG_20211103_095812.jpg](https://user-images.githubusercontent.com/41317284/140000364-7ecd11d0-ed11-438c-9b11-5202a24b7bb8.jpg)

点击时样式
![IMG_20211103_095839.jpg](https://user-images.githubusercontent.com/41317284/140000370-bb8c74ae-baa0-45cb-a91a-7d5e5ed694de.jpg)
