### ISSUE TITLE
[Bug Report] van-popover如何设置宽度？

### ISSUE THREAD

**Issue by FreedomFoolt** [youzan/vant#9630]
### 设备 / 浏览器
Chrome

### Vant 版本
3.2.3

### Vue 版本
3.2.0

### 描述问题
即使使用v-deep样式穿透也无法将样式`width`添加到van-popover上，如何设置popover的宽度呢？

```css
::v-deep(.van-popover) {
  width: 3rem !important;
}
```
